# Project: AFND-a-AFD
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = AND-to-AD.o Automata.o Estado.o Funcion.o
LINKOBJ  = AND-to-AD.o Automata.o Estado.o Funcion.o
LIBS     = -L"G:/Programas/Dev-C++Portable/MinGW32/lib" -L"G:/Programas/Dev-C++Portable/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc
INCS     = -I"G:/Programas/Dev-C++Portable/MinGW32/include" -I"G:/Programas/Dev-C++Portable/MinGW32/mingw32/include" -I"G:/Programas/Dev-C++Portable/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"G:/Programas/Dev-C++Portable/MinGW32/include" -I"G:/Programas/Dev-C++Portable/MinGW32/mingw32/include" -I"G:/Programas/Dev-C++Portable/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"G:/Programas/Dev-C++Portable/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = AFND-a-AFD.exe
CXXFLAGS = $(CXXINCS) -std=gnu++11
CFLAGS   = $(INCS) -std=gnu++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

AND-to-AD.o: AND-to-AD.cpp
	$(CPP) -c AND-to-AD.cpp -o AND-to-AD.o $(CXXFLAGS)

Automata.o: Automata.cpp
	$(CPP) -c Automata.cpp -o Automata.o $(CXXFLAGS)

Estado.o: Estado.cpp
	$(CPP) -c Estado.cpp -o Estado.o $(CXXFLAGS)

Funcion.o: Funcion.cpp
	$(CPP) -c Funcion.cpp -o Funcion.o $(CXXFLAGS)
